services:
  - type: web
    name: session-slack
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 2
    envVars:
      - key: SHOPIFY_STORE
        value: fragrantsouq.myshopify.com
      - key: SHOPIFY_ACCESS_TOKEN
        sync: false
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_CHANNEL_ID
        value: C0B9V9U312L
